# Generated by Django 4.2.7 on 2026-01-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Date et heure programmée')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure réelle')),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('completed', 'Réalisée'), ('cancelled', 'Annulée'), ('absent', 'Absent'), ('rescheduled', 'Reprogrammée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison de la visite')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='Tension systolique')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Tension diastolique')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie (g/L)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('prescriptions', models.TextField(blank=True, null=True, verbose_name='Prescriptions')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommandations')),
                ('decision', models.CharField(blank=True, choices=[('apte', 'Apte'), ('apte_avec_reserves', 'Apte avec réserves'), ('inapte_temporaire', 'Inapte temporaire'), ('inapte_permanent', 'Inapte permanent'), ('inapte_poste', 'Inapte au poste')], max_length=30, null=True, verbose_name='Décision médicale')),
                ('decision_details', models.TextField(blank=True, null=True, verbose_name='Détails de la décision')),
                ('alert_rh', models.BooleanField(default=False, verbose_name='Alerte RH')),
                ('alert_direction', models.BooleanField(default=False, verbose_name='Alerte Direction')),
                ('alert_reason', models.TextField(blank=True, null=True, verbose_name="Raison de l'alerte")),
                ('rescheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Date reprogrammée')),
                ('rescheduling_reason', models.TextField(blank=True, null=True, verbose_name='Raison de la reprogrammation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validée (non modifiable)')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_nurse', to=settings.AUTH_USER_MODEL, verbose_name='Infirmier')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'verbose_name_plural': 'Visites médicales',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de visite',
                'verbose_name_plural': 'Types de visites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitConvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('sent_via', models.CharField(default='email', max_length=50, verbose_name="Moyen d'envoi")),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Accusé de réception')),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'accusé de réception")),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convocation', to='visits.medicalvisit', verbose_name='Visite')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
            },
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visits.visittype', verbose_name='Type de visite'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['agent', '-scheduled_date'], name='visits_medi_agent_i_696293_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['status', '-scheduled_date'], name='visits_medi_status_e0da5c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['is_validated'], name='visits_medi_is_vali_a31bd1_idx'),
        ),
    ]
