# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalvisit',
            old_name='decision',
            new_name='avis',
        ),
        migrations.RenameField(
            model_name='medicalvisit',
            old_name='decision_details',
            new_name='avis_details',
        ),
    ]
