# Generated by Django 4.2.7 on 2026-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_rename_decision_to_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalvisit',
            name='avis',
            field=models.CharField(blank=True, choices=[('apte', 'Apte'), ('apte_avec_reserves', 'Apte avec réserves'), ('inapte_temporaire', 'Inapte temporaire'), ('inapte_permanent', 'Inapte permanent'), ('inapte_poste', 'Inapte au poste')], max_length=30, null=True, verbose_name='Avis médical'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='avis_details',
            field=models.TextField(blank=True, null=True, verbose_name="Détails de l'avis"),
        ),
    ]
