# Generated by Django 4.2.7 on 2026-03-04 23:52

import consultations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0006_dmst_observation_form_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message / précisions')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Créneau souhaité')),
                ('meeting_id', models.CharField(default=consultations.models.generate_meeting_id, editable=False, max_length=50, unique=True, verbose_name='ID de la salle')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Programmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure programmées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_consultations', to='medical.agent', verbose_name='Agent')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_requested', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
            ],
            options={
                'verbose_name': 'Consultation en ligne',
                'verbose_name_plural': 'Consultations en ligne',
                'ordering': ['-created_at'],
            },
        ),
    ]
