# Generated by Django 4.2.7 on 2026-01-29 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prevention', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0001_initial'),
        ('medical', '0003_add_related_visit_to_dmst_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du vaccin')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('validity_period_months', models.IntegerField(blank=True, null=True, verbose_name='Période de validité (mois)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Vaccin',
                'verbose_name_plural': 'Vaccins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_requirements', to='companies.jobposition', verbose_name='Poste de travail')),
                ('risk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_requirements', to='prevention.riskcategory', verbose_name='Catégorie de risque')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='vaccination.vaccine', verbose_name='Vaccin')),
            ],
            options={
                'verbose_name': 'Vaccination obligatoire / recommandée',
                'verbose_name_plural': 'Vaccinations obligatoires / recommandées',
                'ordering': ['vaccine'],
            },
        ),
        migrations.CreateModel(
            name='VaccineContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Raison de la contre-indication')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de constat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_contraindications', to='medical.agent', verbose_name='Agent')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_contraindications_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Constaté par')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='vaccination.vaccine', verbose_name='Vaccin')),
            ],
            options={
                'verbose_name': 'Contre-indication vaccinale',
                'verbose_name_plural': 'Contre-indications vaccinales',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('due_soon', 'À échéance'), ('overdue', 'En retard')], max_length=20, verbose_name="Type d'alerte")),
                ('due_date', models.DateField(verbose_name='Date de rappel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Pris en compte')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Pris en compte le')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_alerts_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='Pris en compte par')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_alerts', to='medical.agent', verbose_name='Agent')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vaccination.vaccine', verbose_name='Vaccin')),
            ],
            options={
                'verbose_name': 'Alerte vaccination',
                'verbose_name_plural': 'Alertes vaccination',
                'ordering': ['due_date', 'agent'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField(verbose_name='Date de vaccination')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de lot')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Date de rappel')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL, verbose_name='Administré par')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='medical.agent', verbose_name='Agent')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='vaccination.vaccine', verbose_name='Vaccin')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_during_visit', to='visits.medicalvisit', verbose_name='Visite médicale associée')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveillance_type', models.CharField(choices=[('quinquennial', 'Quinquennale'), ('specific', 'Spécifique'), ('chronic', 'Maladie chronique')], max_length=20, verbose_name='Type de surveillance')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Date de prochaine révision')),
                ('reason', models.TextField(verbose_name='Raison de la surveillance')),
                ('medical_findings', models.TextField(blank=True, null=True, verbose_name='Constats médicaux')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommandations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='medical.agent', verbose_name='Agent')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillances_prescribed', to=settings.AUTH_USER_MODEL, verbose_name='Prescrit par')),
            ],
            options={
                'verbose_name': 'Surveillance médicale',
                'verbose_name_plural': 'Surveillances médicales',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='vaccinerequirement',
            constraint=models.CheckConstraint(check=models.Q(('job_position__isnull', False), ('risk_category__isnull', False), _connector='OR'), name='vaccine_requirement_job_or_risk'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinecontraindication',
            unique_together={('agent', 'vaccine')},
        ),
        migrations.AddIndex(
            model_name='vaccinationalert',
            index=models.Index(fields=['alert_type', 'due_date'], name='vaccination_alert_t_71ee91_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationalert',
            index=models.Index(fields=['acknowledged'], name='vaccination_acknowl_dc4bac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccination',
            unique_together={('agent', 'vaccine', 'vaccination_date')},
        ),
    ]
