# Generated by Django 4.2.7 on 2026-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='dose_interval_months',
            field=models.IntegerField(choices=[(1, '1 mois'), (6, '6 mois')], default=1, verbose_name='Intervalle entre doses (mois)'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dose_number',
            field=models.IntegerField(choices=[(1, '1ère dose'), (2, '2ème dose'), (3, '3ème dose')], default=1, verbose_name='Numéro de dose'),
        ),
    ]
