# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_vaccination_dose_interval_months_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='notes',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='vaccinecontraindication',
            old_name='notes',
            new_name='observation',
        ),
    ]
