# Generated by Django 4.2.7 on 2026-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_notes_to_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='vaccinecontraindication',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
