# Generated by Django 4.2.7 on 2026-01-29 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0003_add_related_visit_to_dmst_history'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('validity_period_months', models.IntegerField(blank=True, null=True, verbose_name='Période de validité (mois)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de formation',
                'verbose_name_plural': 'Types de formations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Date de prochain rappel')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=20, verbose_name='Statut')),
                ('training_organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisme formateur')),
                ('trainer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formateur')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Résultat')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de certificat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_created', to=settings.AUTH_USER_MODEL)),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='training.trainingtype', verbose_name='Type de formation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('theme', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thématique')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Liens')),
                ('target_audience', models.CharField(choices=[('all', 'Tous les agents'), ('category', 'Par catégorie'), ('surveillance', 'Agents sous surveillance'), ('specific', 'Agents spécifiques')], default='all', max_length=20, verbose_name='Public cible')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_authored', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Article éducatif',
                'verbose_name_plural': 'Articles éducatifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='companies.jobposition', verbose_name='Poste de travail')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='training.trainingtype', verbose_name='Type de formation')),
            ],
            options={
                'verbose_name': 'Formation obligatoire / recommandée',
                'verbose_name_plural': 'Formations obligatoires / recommandées',
                'ordering': ['job_position', 'training_type'],
                'unique_together': {('training_type', 'job_position')},
            },
        ),
        migrations.CreateModel(
            name='ArticleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_articles', to='medical.agent', verbose_name='Agent')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='training.educationalarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Destinataire d'article",
                'verbose_name_plural': "Destinataires d'articles",
                'unique_together': {('article', 'agent')},
            },
        ),
    ]
