# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Drive (cours)'),
        ),
    ]
