# Generated by Django 4.2.7 on 2026-02-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_dmst_observation_form_data'),
        ('training', '0002_trainingtype_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='participants_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Effectif (nombre de participants)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='medical.agent', verbose_name='Agent'),
        ),
    ]
