# Generated by Django 4.2.16 on 2026-06-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_medicalresult_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0003_add_participants_count_effectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Date de prochain rappel')),
                ('training_organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisme formateur')),
                ('trainer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formateur')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Résultat')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de certificat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_created', to=settings.AUTH_USER_MODEL)),
                ('training_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_certifications', to='training.trainingrequirement', verbose_name='Formation requise')),
            ],
            options={
                'verbose_name': 'Certification agent',
                'verbose_name_plural': 'Certifications agents',
                'ordering': ['-start_date'],
                'unique_together': {('agent', 'training_requirement')},
            },
        ),
    ]
