# Generated by Django 4.2.7 on 2026-01-29 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0003_add_related_visit_to_dmst_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de risque',
                'verbose_name_plural': 'Catégories de risques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du risque')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20, verbose_name='Gravité')),
                ('probability', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20, verbose_name='Probabilité')),
                ('exposure_frequency', models.CharField(blank=True, max_length=200, null=True, verbose_name="Fréquence d'exposition")),
                ('identification_date', models.DateField(verbose_name="Date d'identification")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='prevention.riskcategory', verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='companies.company', verbose_name='Entreprise')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_identified', to=settings.AUTH_USER_MODEL, verbose_name='Identifié par')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='companies.jobposition', verbose_name='Poste de travail')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='companies.service', verbose_name='Service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='companies.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Risque professionnel',
                'verbose_name_plural': 'Risques professionnels',
                'ordering': ['-identification_date'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], max_length=20, verbose_name="Type d'action")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('planned_date', models.DateField(verbose_name='Date prévue')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=20, verbose_name='Statut')),
                ('effectiveness', models.TextField(blank=True, null=True, verbose_name='Efficacité')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='prevention.risk', verbose_name='Risque')),
            ],
            options={
                'verbose_name': 'Action préventive/corrective',
                'verbose_name_plural': 'Actions préventives/correctives',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='IndividualRiskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risks_description', models.TextField(verbose_name='Description des risques')),
                ('preventive_measures', models.TextField(blank=True, null=True, verbose_name='Mesures préventives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_sheet', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche individuelle des risques',
                'verbose_name_plural': 'Fiches individuelles des risques',
            },
        ),
        migrations.CreateModel(
            name='IndividualExposureSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_period', models.CharField(max_length=200, verbose_name="Période d'exposition")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_sheet', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exposed_risks', models.ManyToManyField(related_name='exposed_agents', to='prevention.risk', verbose_name='Risques exposés')),
            ],
            options={
                'verbose_name': "Fiche individuelle d'exposition",
                'verbose_name_plural': "Fiches individuelles d'exposition",
            },
        ),
    ]
