# Generated by Django 4.2.7 on 2026-01-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
        ('prevention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('physical', 'Physique'), ('biological', 'Biologique'), ('chemical', 'Chimique'), ('psychosocial', 'Psychosocial'), ('ergonomic', 'Ergonomique')], max_length=20, null=True, verbose_name='Type de catégorie'),
        ),
        migrations.CreateModel(
            name='RiskWorkAccidentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_accident_links', to='prevention.risk', verbose_name='Risque')),
                ('work_accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='accidents.workaccident', verbose_name='Accident de travail')),
            ],
            options={
                'verbose_name': 'Lien risque – accident de travail',
                'verbose_name_plural': 'Liens risque – accidents de travail',
                'ordering': ['-created_at'],
                'unique_together': {('risk', 'work_accident')},
            },
        ),
        migrations.CreateModel(
            name='RiskOccupationalDiseaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupational_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='accidents.occupationaldisease', verbose_name='Maladie professionnelle')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupational_disease_links', to='prevention.risk', verbose_name='Risque')),
            ],
            options={
                'verbose_name': 'Lien risque – maladie professionnelle',
                'verbose_name_plural': 'Liens risque – maladies professionnelles',
                'ordering': ['-created_at'],
                'unique_together': {('risk', 'occupational_disease')},
            },
        ),
    ]
