# Generated by Django 4.2.7 on 2026-01-29 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('title', models.CharField(blank=True, choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MLLE', 'Mademoiselle')], max_length=10, null=True, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom du contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone du contact d'urgence")),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Relation avec le contact d'urgence")),
                ('function', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonction')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade')),
                ('professional_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie professionnelle')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_agents', to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='companies.jobposition', verbose_name='Poste de travail')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='companies.service', verbose_name='Service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='companies.site', verbose_name='Site')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='medical.agent', verbose_name='Supérieur hiérarchique')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agents', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code CIM-10')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pathologie',
                'verbose_name_plural': 'Pathologies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DMST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('smoking', models.BooleanField(default=False, verbose_name='Tabagisme')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Alcool')),
                ('drugs', models.BooleanField(default=False, verbose_name='Drogues')),
                ('habits_notes', models.TextField(blank=True, null=True, verbose_name='Notes sur les habitudes')),
                ('physical_pathologies', models.TextField(blank=True, null=True, verbose_name='Pathologies physiques')),
                ('mental_pathologies', models.TextField(blank=True, null=True, verbose_name='Pathologies mentales')),
                ('social_pathologies', models.TextField(blank=True, null=True, verbose_name='Pathologies sociales')),
                ('hereditary_diseases', models.TextField(blank=True, null=True, verbose_name='Maladies héréditaires')),
                ('handicap', models.BooleanField(default=False, verbose_name='Handicap')),
                ('handicap_details', models.TextField(blank=True, null=True, verbose_name='Détails du handicap')),
                ('pregnancy', models.BooleanField(default=False, verbose_name='Grossesse')),
                ('pregnancy_due_date', models.DateField(blank=True, null=True, verbose_name="Date prévue d'accouchement")),
                ('current_treatments', models.TextField(blank=True, null=True, verbose_name='Traitements en cours')),
                ('treating_doctors', models.TextField(blank=True, null=True, verbose_name='Médecins traitants')),
                ('working_conditions', models.TextField(blank=True, null=True, verbose_name='Conditions de travail')),
                ('under_surveillance', models.BooleanField(default=False, verbose_name='Sous surveillance médicale')),
                ('surveillance_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de surveillance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dmst', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmst_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmst_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMST',
                'verbose_name_plural': 'DMST',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(verbose_name='Date de diagnostic')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologies', to='medical.agent')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='medical.pathology')),
            ],
            options={
                'verbose_name': 'Pathologie agent',
                'verbose_name_plural': 'Pathologies agents',
                'unique_together': {('agent', 'pathology')},
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['matricule'], name='medical_age_matricu_dec6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['company', 'site', 'service'], name='medical_age_company_e924c8_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active', 'is_archived'], name='medical_age_is_acti_b748ca_idx'),
        ),
    ]
