# Generated by Django 4.2.7 on 2026-01-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmst',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Maladies chroniques'),
        ),
        migrations.CreateModel(
            name='DMSTHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('modification_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('visit', 'Visite médicale'), ('diagnosis', 'Diagnostic'), ('prescription', 'Prescription')], max_length=50, verbose_name='Type de modification')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Champ modifié')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison de la modification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('dmst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medical.dmst', verbose_name='DMST')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmst_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Historique DMST',
                'verbose_name_plural': 'Historiques DMST',
                'ordering': ['-modification_date'],
                'indexes': [models.Index(fields=['dmst', '-modification_date'], name='medical_dms_dmst_id_355fab_idx'), models.Index(fields=['modified_by', '-modification_date'], name='medical_dms_modifie_07215f_idx')],
            },
        ),
    ]
