# Generated by Django 4.2.7 on 2026-01-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        ('medical', '0002_dmst_chronic_diseases_dmsthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsthistory',
            name='related_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmst_changes', to='visits.medicalvisit', verbose_name='Visite associée'),
        ),
    ]
