# Generated by Django 4.2.7 on 2026-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_add_related_visit_to_dmst_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmst',
            name='clinical_signs',
            field=models.TextField(blank=True, null=True, verbose_name='Signes cliniques'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='complementary_exams',
            field=models.TextField(blank=True, null=True, verbose_name='Examens complémentaires'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusion'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'observation"),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Notes d'observation"),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'observateur"),
        ),
    ]
