# Generated by Django 4.2.7 on 2026-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_dmst_clinical_signs_dmst_complementary_exams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmst',
            name='clinical_signs',
        ),
        migrations.RemoveField(
            model_name='dmst',
            name='complementary_exams',
        ),
        migrations.RemoveField(
            model_name='dmst',
            name='observation_conclusion',
        ),
        migrations.RemoveField(
            model_name='dmst',
            name='observation_notes',
        ),
        migrations.RemoveField(
            model_name='dmst',
            name='observation_recommendations',
        ),
        migrations.AddField(
            model_name='dmst',
            name='alcohol_obs',
            field=models.BooleanField(default=False, verbose_name='Alcool'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='at_mp_nature',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AT/MP (12 derniers mois) - Nature'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='blood_pressure_diastolic',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TA Diastolique'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='blood_pressure_systolic',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TA Systolique'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC (kg/m²)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='clinical_exam',
            field=models.TextField(blank=True, null=True, verbose_name='Examen clinique'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='coffee',
            field=models.BooleanField(default=False, verbose_name='Café'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='dextro_jn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dextro (jn)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='dextro_pp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dextro (pp)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_ergo',
            field=models.BooleanField(default=False, verbose_name='Ergo'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_fdr_cvx',
            field=models.BooleanField(default=False, verbose_name='FDR-CVx'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_mhd',
            field=models.BooleanField(default=False, verbose_name='MHD'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_mhv',
            field=models.BooleanField(default=False, verbose_name='MHV'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Autre (éducation)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_spb_psy',
            field=models.BooleanField(default=False, verbose_name='SPB&Psy'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='education_therapy',
            field=models.BooleanField(default=False, verbose_name='Thérapie'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fréquence cardiaque (FC)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_antecedents',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_conclusion_aar',
            field=models.BooleanField(default=False, verbose_name='AAR'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_conclusion_apte',
            field=models.BooleanField(default=False, verbose_name='Apte'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_conclusion_asr',
            field=models.BooleanField(default=False, verbose_name='ASR'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_conclusion_ind',
            field=models.BooleanField(default=False, verbose_name='IND'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='medical_conclusion_int',
            field=models.BooleanField(default=False, verbose_name='INT'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_direction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_function',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='observation_site',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='physical_activity',
            field=models.BooleanField(default=False, verbose_name='Activité physique'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='previous_companies',
            field=models.TextField(blank=True, null=True, verbose_name='Entreprises antérieures'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='sport_activity',
            field=models.BooleanField(default=False, verbose_name='Activité sportive'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='surgical_antecedents',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédents chirurgicaux'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='tea',
            field=models.BooleanField(default=False, verbose_name='Thé'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Température'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='tobacco',
            field=models.BooleanField(default=False, verbose_name='Tabac'),
        ),
        migrations.AddField(
            model_name='dmst',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='dmst',
            name='observer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du médecin du travail'),
        ),
    ]
