# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_remove_dmst_clinical_signs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmst',
            name='observation_form_data',
            field=models.JSONField(blank=True, null=True, verbose_name="Fiche d'observation (données complètes)"),
        ),
    ]
