# Generated by Django 4.2.16 on 2026-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_dmst_observation_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
