# Generated by Django 4.2.16 on 2026-08-05 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0004_add_consultation_visit_type'),
        ('medical', '0009_medicalresult_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de la consultation')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif de consultation')),
                ('diagnostic_principal', models.TextField(blank=True, null=True, verbose_name='Diagnostic principal')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Contenu de la consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical.agent', verbose_name='Agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_updated', to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='visits.visittype', verbose_name='Type de visite')),
            ],
            options={
                'verbose_name': 'Consultation médicale',
                'verbose_name_plural': 'Consultations médicales',
                'ordering': ['-consultation_date'],
                'indexes': [models.Index(fields=['agent', '-consultation_date'], name='medical_med_agent_i_a4a2b4_idx')],
            },
        ),
    ]
