# Generated by Django 4.2.16 on 2026-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_medicalconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation',
            name='kind',
            field=models.CharField(choices=[('observation', "Fiche d'observation"), ('consultation', 'Consultation médicale')], default='consultation', max_length=20, verbose_name='Type de fiche'),
        ),
        migrations.AddIndex(
            model_name='medicalconsultation',
            index=models.Index(fields=['agent', 'kind', '-consultation_date'], name='medical_med_agent_i_f02f3b_idx'),
        ),
    ]
