# Generated by Django 4.2.7 on 2026-01-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0003_add_related_visit_to_dmst_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDataAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100, verbose_name='Type de données')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('reason', models.TextField(blank=True, null=True, verbose_name="Raison de l'accès")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='medical.agent', verbose_name='Agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès données médicales',
                'verbose_name_plural': 'Accès données médicales',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_medic_timesta_cbc714_idx'), models.Index(fields=['user', '-timestamp'], name='audit_medic_user_id_5858af_idx'), models.Index(fields=['agent', '-timestamp'], name='audit_medic_agent_i_e77f38_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=20, verbose_name="Type d'action")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name="Représentation de l'objet")),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_audit_action__32de6f_idx')],
            },
        ),
    ]
