# Generated by Django 4.2.7 on 2026-01-29 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0003_add_related_visit_to_dmst_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, verbose_name='Nom de la maladie')),
                ('disease_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code maladie')),
                ('first_symptoms_date', models.DateField(verbose_name='Date des premiers symptômes')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Date de diagnostic')),
                ('status', models.CharField(choices=[('suspected', 'Suspectée'), ('declared', 'Déclarée'), ('recognized', 'Reconnue'), ('rejected', 'Rejetée')], default='suspected', max_length=20, verbose_name='Statut')),
                ('exposure_period', models.CharField(blank=True, max_length=200, null=True, verbose_name="Période d'exposition")),
                ('exposure_factors', models.TextField(blank=True, null=True, verbose_name="Facteurs d'exposition")),
                ('medical_follow_up', models.TextField(blank=True, null=True, verbose_name='Suivi médical')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Traitement')),
                ('declaration_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('recognition_date', models.DateField(blank=True, null=True, verbose_name='Date de reconnaissance')),
                ('recognition_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de reconnaissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupational_diseases', to='medical.agent', verbose_name='Agent')),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases_declared', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
            ],
            options={
                'verbose_name': 'Maladie professionnelle',
                'verbose_name_plural': 'Maladies professionnelles',
                'ordering': ['-first_symptoms_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type', models.CharField(choices=[('work', 'Accident de travail'), ('commute', 'Accident de trajet'), ('service', 'Accident de service')], default='work', max_length=20, verbose_name="Type d'accident")),
                ('accident_date', models.DateTimeField(verbose_name="Date et heure de l'accident")),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('circumstances', models.TextField(verbose_name='Circonstances')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('severity', models.CharField(choices=[('light', 'Léger'), ('moderate', 'Modéré'), ('severe', 'Grave'), ('fatal', 'Mortel')], max_length=20, verbose_name='Gravité')),
                ('status', models.CharField(choices=[('declared', 'Déclaré'), ('investigating', "En cours d'investigation"), ('closed', 'Clôturé')], default='declared', max_length=20, verbose_name='Statut')),
                ('work_stoppage', models.BooleanField(default=False, verbose_name='Arrêt de travail')),
                ('work_stoppage_days', models.IntegerField(blank=True, null=True, verbose_name="Nombre de jours d'arrêt")),
                ('medical_care', models.BooleanField(default=False, verbose_name='Soins médicaux')),
                ('hospitalization', models.BooleanField(default=False, verbose_name='Hospitalisation')),
                ('root_causes', models.TextField(blank=True, null=True, verbose_name='Causes racines')),
                ('contributing_factors', models.TextField(blank=True, null=True, verbose_name='Facteurs contributifs')),
                ('corrective_actions', models.TextField(blank=True, null=True, verbose_name='Actions correctives')),
                ('preventive_actions', models.TextField(blank=True, null=True, verbose_name='Actions préventives')),
                ('declaration_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('alert_rh', models.BooleanField(default=False, verbose_name='Alerte RH')),
                ('alert_direction', models.BooleanField(default=False, verbose_name='Alerte Direction')),
                ('alert_hse', models.BooleanField(default=False, verbose_name='Alerte HSE')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi des alertes")),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='medical.agent', verbose_name='Agent')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_closed', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_declared', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
            ],
            options={
                'verbose_name': 'Accident de travail',
                'verbose_name_plural': 'Accidents de travail',
                'ordering': ['-accident_date'],
                'indexes': [models.Index(fields=['accident_type', '-accident_date'], name='accidents_w_acciden_b3e327_idx'), models.Index(fields=['severity', '-accident_date'], name='accidents_w_severit_c50a58_idx'), models.Index(fields=['status', '-accident_date'], name='accidents_w_status_a7a591_idx'), models.Index(fields=['agent', '-accident_date'], name='accidents_w_agent_i_6df2c3_idx')],
            },
        ),
    ]
