# Generated by Django 4.2.7

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workaccident',
            old_name='circumstances',
            new_name='mechanism',
        ),
        migrations.AddField(
            model_name='workaccident',
            name='return_to_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de reprise'),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='ipp',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
                verbose_name='IPP (%)',
            ),
        ),
        migrations.AlterField(
            model_name='workaccident',
            name='accident_type',
            field=models.CharField(
                choices=[
                    ('work', 'Accident de travail'),
                    ('commute', 'Accident de trajet'),
                    ('service', 'Accident de service'),
                    ('mission', 'Accident de mission'),
                ],
                default='work',
                max_length=20,
                verbose_name="Type d'accident",
            ),
        ),
    ]
