# Generated by Django 4.2.7

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import migrations, models
import django.db.models.deletion


def migrate_suspected_to_declared(apps, schema_editor):
    OccupationalDisease = apps.get_model('accidents', 'OccupationalDisease')
    OccupationalDisease.objects.filter(status='suspected').update(status='declared')


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_mechanism_reprise_ipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationaldisease',
            name='disease_type',
            field=models.CharField(
                choices=[
                    ('mp', 'Maladie professionnelle'),
                    ('mcp', 'Maladie à caractère professionnel'),
                    ('ms', 'Maladie suspecte'),
                ],
                default='mp',
                max_length=10,
                verbose_name='Type',
            ),
        ),
        migrations.AddField(
            model_name='occupationaldisease',
            name='table_number',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[MinValueValidator(1), MaxValueValidator(100)],
                verbose_name='Numéro de tableau',
            ),
        ),
        migrations.AddField(
            model_name='occupationaldisease',
            name='return_delay',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
                verbose_name='Délai de reprise',
            ),
        ),
        migrations.AddField(
            model_name='occupationaldisease',
            name='exposure_start_date',
            field=models.DateField(blank=True, null=True, verbose_name="Début d'exposition"),
        ),
        migrations.AddField(
            model_name='occupationaldisease',
            name='exposure_end_date',
            field=models.DateField(blank=True, null=True, verbose_name="Fin d'exposition"),
        ),
        migrations.RunPython(migrate_suspected_to_declared, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='occupationaldisease',
            name='status',
            field=models.CharField(
                choices=[
                    ('declared', 'Déclarée'),
                    ('recognized', 'Reconnue'),
                    ('rejected', 'Rejetée'),
                ],
                default='declared',
                max_length=20,
                verbose_name='Statut',
            ),
        ),
        migrations.AlterField(
            model_name='occupationaldisease',
            name='disease_name',
            field=models.CharField(max_length=200, verbose_name='Désignation maladie'),
        ),
        migrations.RemoveField(
            model_name='occupationaldisease',
            name='disease_code',
        ),
        migrations.RemoveField(
            model_name='occupationaldisease',
            name='exposure_period',
        ),
    ]
