# Generated by Django 4.2.7 on 2026-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_occupational_disease_form_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workaccident',
            name='mechanism',
            field=models.TextField(verbose_name='Mécanisme'),
        ),
    ]
