# Generated by Django 4.2.7 on 2026-03-23 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0004_alter_workaccident_mechanism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationaldisease',
            name='return_delay',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Durée d'absence (jours)"),
        ),
    ]
